package md

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/wohsj110/atlassian_cli/shared/testutil"
)

var update = flag.Bool("update", false, "update golden files")

// TestFidelity_FromConfluenceStorage validates XHTML→markdown conversion fidelity
// using real Confluence page fixtures.
//
// Fixtures are generated by scripts/roundtrip-test.sh against live Confluence pages.
// Each fixture pair consists of:
//   - <page-id>.before.xhtml — original Confluence storage format
//   - <page-id>.golden.md — expected markdown output (human-reviewed)
//
// Run with -update to regenerate golden files:
//
//	go test ./pkg/md/... -update
func TestFidelity_FromConfluenceStorage(t *testing.T) {
	t.Parallel()

	fixtureDir := "testdata/roundtrip"
	pattern := filepath.Join(fixtureDir, "*.before.xhtml")

	matches, err := filepath.Glob(pattern)
	if err != nil {
		t.Fatalf("globbing fixtures: %v", err)
	}

	if len(matches) == 0 {
		t.Skip("no fixtures in testdata/roundtrip/ — run scripts/roundtrip-test.sh to generate")
	}

	for _, beforePath := range matches {
		beforePath := beforePath // capture for parallel
		// Extract page ID from filename: "12345.before.xhtml" → "12345"
		base := filepath.Base(beforePath)
		pageID := strings.TrimSuffix(base, ".before.xhtml")
		goldenPath := filepath.Join(fixtureDir, pageID+".golden.md")

		t.Run(pageID, func(t *testing.T) {
			t.Parallel()

			// Read XHTML fixture
			xhtml, err := os.ReadFile(beforePath) //nolint:gosec // test fixture path
			if err != nil {
				t.Fatalf("reading %s: %v", beforePath, err)
			}

			// Convert to markdown with macros shown (matches roundtrip-test.sh)
			got, err := FromConfluenceStorageWithOptions(string(xhtml), ConvertOptions{
				ShowMacros: true,
			})
			if err != nil {
				t.Fatalf("converting XHTML→MD: %v", err)
			}

			if *update {
				if err := os.WriteFile(goldenPath, []byte(got), 0600); err != nil { //nolint:gosec // test golden file path
					t.Fatalf("writing golden file: %v", err)
				}
				t.Logf("updated %s", goldenPath)
				return
			}

			// Read expected markdown
			want, err := os.ReadFile(goldenPath) //nolint:gosec // test fixture path
			if err != nil {
				if os.IsNotExist(err) {
					t.Fatalf("golden file missing: %s (run with -update to create)", goldenPath)
				}
				t.Fatalf("reading %s: %v", goldenPath, err)
			}

			testutil.Equal(t, string(want), got)
		})
	}
}
